server:
  port: 80
spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: thongnguyen
  jackson:
    default-property-inclusion: non_null