server:
  port: 80
spring:
  main:
    web-application-type: servlet
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      port: 27017
      database: thongnguyen
      host: localhost
